# Generated by Django 4.2.9 on 2024-02-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_query_querycomment_classschedule_classattendance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course", old_name="descriptionn", new_name="description",
        ),
    ]
