# Generated by Django 4.2.9 on 2024-02-15 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_rename_descriptionn_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classattendance",
            name="attendee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attended_classes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="classattendance",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(model_name="classattendance", name="class_schedule",),
        migrations.AlterField(
            model_name="classattendance",
            name="is_present",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_schedules",
                to="users.cohort",
            ),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="description",
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="end_date_and_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="is_repeated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="organizer",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_classes",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="repeat_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="start_date_and_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="classschedule",
            name="venue",
            field=models.CharField(
                blank=True, default=django.utils.timezone.now, max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, default="N/A", null=True),
        ),
        migrations.AlterField(
            model_name="course", name="name", field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="query",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="query",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="query_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="query",
            name="description",
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="query",
            name="resolution_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DECLINED", "Declined"),
                    ("RESOLVED", "Resolved"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="query",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="query", name="title", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="querycomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="querycomment", name="comment", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="querycomment",
            name="query",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="main.query",
            ),
        ),
        migrations.AddField(
            model_name="classattendance",
            name="class_schedule",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="main.classschedule",
            ),
            preserve_default=False,
        ),
    ]
