# Generated by Django 4.2.9 on 2024-02-22 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0005_alter_classattendance_attendee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classschedule",
            name="Course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_schedule_course",
                to="main.course",
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="facilitator",
            field=models.ForeignKey(
                blank=True,
                choices=[
                    ("CLASS_SESSIONS", "Class Sessions"),
                    ("WELLNESS_SESSIONS", "Wellness Sessions"),
                    ("GUEST_LECTURES", "Gues Lesture"),
                ],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_schedule_facilitator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
